---

- name: Playbook for creating users
  hosts: all
  become: yes

  tasks:
    - name: Create User 'george'
      ansible.builtin.user:
        name: george
        home: /home/george
        shell: /bin/bash
        create_home: yes
        state: present
