---

- name: Add or update new password
  hosts: all
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Change "george" password
      ansible.builtin.user:
        name: george
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"
