---
- name: File status module
  hosts: localhost

  tasks:
    - name: check file status and attributes
      stat:
        path: /etc/hosts
      register: fs

    - name: Show result
      debug:
        msg: File attributes {{ fs }}

