---

- name: Install packages through loop
  hosts: local host
  vars:
    packages: [ftp,telnet,htop]

  tasks:
    - name: Install Packages
      apt:
        name: '{{items}}'
        state: present  
      with_items: '{{packages}}'
